services:
  irma:
    image: ghcr.io/privacybydesign/irma:main
    restart: always
    command: server -v
    environment:
      IRMASERVER_NO_AUTH: 0
      IRMASERVER_NO_EMAIL: 1
      IRMASERVER_NO_TLS: 1
      IRMASERVER_PRODUCTION: 1
      IRMASERVER_URL: https://diyivi.ddoesburg.nl/yivi/
      # Configure the key that the API can sign session request JWTs with.
      # WARNING: this is a placeholder key. Generate a secret one for production use.
      IRMASERVER_REQUESTORS: '{
        "diyivi": {
          "auth_method": "hmac",
          "key": "dW5zYWZlX3NlY3JldF9rZXk=",
          "disclose_perms": ["*"]
        },
        "client": {
          "auth_method": "hmac",
          "key": "c2lnbmF0dXJlcy1jYW4tYmUtY3JlYXRlZC1ieS1hbnlvbmU=",
          "sign_perms": ["*"]
        }
      }'
      # Configure the key that the irma server can sign session result JWTs with.
      IRMASERVER_JWT_PRIVKEY_file: /run/secrets/irmaserver-jwt-privkey
    secrets:
      - irmaserver-jwt-privkey

  server:
    image: ghcr.io/ded1rk/diyivi-server:main
    restart: always
    environment:
      BASE_URL: https://diyivi.ddoesburg.nl/
      CLIENT_ORIGIN: https://diyivi.ddoesburg.nl
      IRMA__SERVER_URL: https://diyivi.ddoesburg.nl/yivi/
      REDIS_URL: redis://redis:6379

  nginx:
    image: ghcr.io/ded1rk/diyivi-nginx:main
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      CERTBOT_EMAIL: dirk.doesburg+diyivi-letsencrypt@gmail.com
      STAGING: 1
    volumes:
      - letsencrypt:/etc/letsencrypt:rw

  redis:
    image: redis:7-alpine
    restart: always

secrets:
  irmaserver-jwt-privkey:
    # WARNING: this is a placeholder key. Generate a secret one for production use.
    # For example, use: openssl genrsa -out irmaserver.key 2048
    file: ./irmaserver_private.pem

volumes:
  letsencrypt:
