services:
  irma-server:
    image: ghcr.io/privacybydesign/irma:latest
    command: server
    environment:
      IRMASERVER_NO_AUTH: 0
      IRMASERVER_NO_EMAIL: 1
      IRMASERVER_NO_TLS: 1
      IRMASERVER_AUGMENT_CLIENT_RETURN_URL: 1
      # Configure the key that the API can sign session request JWTs with.
      # WARNING: this is a placeholder key. Generate a secret one for production use.
      IRMASERVER_REQUESTORS: '{"diyivi": {"auth_method": "hmac", "key": "dW5zYWZlX3NlY3JldF9rZXkK"}}'
      # Configure the key that the irma server can sign session result JWTs with.
      IRMASERVER_JWT_PRIVKEY_file: /run/secrets/irmaserver-jwt-privkey
    secrets:
      - irmaserver-jwt-privkey

secrets:
  irmaserver-jwt-privkey:
    # WARNING: this is a placeholder key. Generate a secret one for production use.
    # For example, use: openssl genrsa -out irmaserver.key 2048
    file: ./irmaserver_private.pem
