---

name: Linting and Testing
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-server:
    name: Linting - server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --frozen

      - name: Run ruff check
        run: uv run ruff check --output-format=github

      - name: Run ruff format
        run: uv run ruff format --check

      - name: Run mypy
        run: uv run mypy .

  test-server:
    name: Testing - server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --frozen

      - name: Run tests
        run: uv run coverage run -m pytest -v

      - name: Coverage report
        run: uv run coverage report --skip-covered -m

      - name: Generate HTML coverage report
        run: uv run coverage html

      - name: Save coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov

  lint-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: ./client

      - run: npm install
      - run: npm run lint
      - run: npm run type-check
      - run: npm run format
